### ISSUE TITLE
Under MiNT no CPXs are shown

### ISSUE THREAD

**Issue by DavidGZ** [freemint/cops#3] opened 2020-05-03 06:38 UTC
With COPS from recent snapshot, none CPXs icons are not shown inside COPS's window. This happen with MiNT+XaAES under EmuTOS it works fine. Tested in 2 setups, with Aranym and real hardware (CT60).

**Comment by th-otto** [comment] 2020-05-04 14:34
That was caused by a bug in libcmini and should be fixed by https://github.com/freemint/libcmini/commit/fcfd6c87eba5d45b3068e7d8fb29cbf3dc7a05bd

**Closed as completed by th-otto** 2020-05-04 14:34 UTC

**Comment by DavidGZ** [comment] 2020-05-05 09:58
I tried a latest snapshot build, but still CPX window appear empty on MiNT.

**Comment by th-otto** [comment] 2020-05-05 10:41
Hm. Could be that i forgot to restart the latest builds, and the snapshot on bintray was still using the old version. Did that now. Can you try again please? Using just the cops archives should do, but the freemint archives should also be updated.

**Comment by DavidGZ** [comment] 2020-05-05 11:02
Yes, it's working now :-). Thanks fixing it!
